# Generated by Django 6.0.5 on 2026-05-22 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('lead', 'Lead'), ('deal', 'Deal'), ('ticket', 'Ticket'), ('company', 'Company'), ('reminder', 'Reminder'), ('delete', 'Deleted Resource')], default='system', max_length=50),
        ),
    ]
