# Generated by Django 6.0.5 on 2026-06-04 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_lead_company'),
        ('tickets', '0002_alter_ticket_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='leads.lead'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='source',
            field=models.CharField(choices=[('Chat', 'Chat'), ('Email', 'Email'), ('Phone', 'Phone'), ('Meeting', 'Meeting')], default='Chat', max_length=50),
        ),
    ]
