# Generated by Django 6.0.5 on 2026-06-01 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealactivity',
            name='created_by_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
